stream_over_http_enabled: true

server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 336h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: uat
      environment: uat
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: ${PROMETHEUS_REMOTE_WRITE_URL}
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: s3
    s3:
      bucket: "observability-uat-036475471569"
      prefix: tempo
      region: "us-east-1"
      endpoint: "s3.us-east-1.amazonaws.com"
      forcepathstyle: false
    wal:
      path: /var/tempo/wal
    cache: none

cache:
  background:
    writeback_goroutines: 0

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both
