[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info

[program:prometheus]
command=/bin/prometheus
    --config.file=/etc/prometheus/prometheus.yaml
    --storage.tsdb.path=/prometheus
    --storage.tsdb.min-block-duration=2h
    --storage.tsdb.max-block-duration=2h
    --web.listen-address=0.0.0.0:9090
    --web.enable-lifecycle
    --web.enable-remote-write-receiver
    --log.level=info
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:thanos-sidecar]
command=/bin/thanos sidecar
    --tsdb.path=/prometheus
    --prometheus.url=http://localhost:9090
    --objstore.config-file=/etc/thanos/sidecar.yaml
    --http-address=0.0.0.0:10902
    --grpc-address=0.0.0.0:10901
    --log.level=info
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
priority=20
